name: th-backend
services:
  backend:
    build:
      context: .
    env_file:
      - path: ./.env.production
    ports:
      - 4200:4200
    depends_on:
      - database

  database:
    image: postgres:alpine
    ports:
      - 5433:5432
    env_file:
      - ./.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
